### ISSUE TITLE
How to only check when clicking the checkbox

### ISSUE THREAD

**Issue by superqd** [jakezatecky/react-checkbox-tree#68] opened 2018-02-06 23:06 UTC
What would be the easiest way, assuming it's possible, to only check a node if the click happens in the checkbox?   Right now, it checks when clicking anything in the node, but I'd like to simply know that the node was clicked (and highlight it) instead of checking in that case.  Basically, I need to maintain a selection state in addition to checked and expanded. I.e., which node is selected.

Is there an easy way for this?

**Comment by jakezatecky** [comment] 2018-02-10 16:04
This is pretty much a duplicate of #28. While the request is reasonable in spirit, the semantic structure of the tree nodes make it to where browsers do not provide a reference to whether the checkbox has been clicked or the text label has been clicked. All we know is that there was a state change to the underlying `input` element.

While I am not entirely opposed to being able to support this, the DOM structure of tree nodes would have to be architected a bit differently and we would lose some semantic meaning. I want to keep the tree as semantic as possible.

Alternatively, if the major class of browsers (Webkit, Gecko, EdgeHTML) would give context to the `event` object referring to which element was clicked (either the `input`, the `label`, or anything else), then I could easily add this in. Unfortunately, this context is not standardized and most browsers do not provide such a context.

I am not opposed to using clever JavaScript to determine the reference DOM node, but from my testing the `event` object really did not provide much of a way determining what was being clicked.

**Closed** 2018-05-08 10:14 UTC
Labels: enhancement
